# Generated by Django 3.2.7 on 2021-09-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_short_name', models.CharField(max_length=50)),
                ('customer_full_name', models.CharField(max_length=150)),
                ('customer_addr1', models.CharField(max_length=200)),
                ('customer_addr2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_no', models.CharField(max_length=10)),
                ('delivery_date', models.DateTimeField()),
                ('customer_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOrderDetail',
            fields=[
                ('delivery_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('so', models.CharField(max_length=10)),
                ('delivery_receive_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOrderDetailReceiveUpdate',
            fields=[
                ('delivery_receive_id', models.AutoField(primary_key=True, serialize=False)),
                ('sum_of_delivery_detail_qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiveOrder',
            fields=[
                ('receive_id', models.AutoField(primary_key=True, serialize=False)),
                ('receive_no', models.CharField(max_length=10)),
                ('receive_date', models.DateTimeField()),
                ('receive_vendor', models.IntegerField()),
                ('receive_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReceiveOrderDetail',
            fields=[
                ('receive_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('receive_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('po', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=50)),
            ],
        ),
    ]
